### PR TITLE
Fix for xemu

### PR DESCRIPTION
**Pull request by matracey**
New commits:
- Updated xemu

### CODE REVIEW

**Review by hermanjustnu — CHANGES_REQUESTED** [review]
desmume should be the latest release published here: https://github.com/TASEmulators/desmume/releases/latest

For the nightly builds, copy your changes into a new manifest named desmume-nightly, and change the version from commit id to the build number from here: https://github.com/TASEmulators/desmume/actions/workflows/build_win.yml?query=branch%3Amaster+is%3Asuccess

Same with xenia-canary, get the build number from here: https://github.com/xenia-canary/xenia-canary/actions/workflows/CI.yml?query=is%3Asuccess+branch%3Acanary_experimental+event%3Apush

**Comment by hermanjustnu** [comment]
Fixes #58

**Comment by matracey** [comment]
@hermanjustnu I dropped the changes that I had merged from @beyondmeat's fork. 

They aren't my changes, so I'm not entirely sure what changes I should make there. I'm just trying to fix xemu.

**Comment by beyondmeat** [comment]
@matracey what ended up being merged didn't fix anything. As you can see multiple emus have not been updated and some fail to install now. (I have had a PR to fix them but looks like that won't be merged). I suggest using https://github.com/borger/scoop-emulators, which I maintain and everything works and is updated constantly. I'm pretty quick to fix anything that breaks.

**Pull request merged**
